# Generated by Django 5.0.6 on 2024-07-14 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_hobby', models.CharField(max_length=120, verbose_name='titre du hobbie')),
                ('info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hobby_info', to='curriculum.curriculum')),
            ],
            options={
                'verbose_name': 'Hobbie',
                'verbose_name_plural': 'Hobbies',
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='hobbies',
            field=models.ManyToManyField(blank=True, related_name='hobbies', to='curriculum.hobby'),
        ),
    ]
