# Generated by Django 5.0.6 on 2024-07-14 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_hobby_curriculum_hobbies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hobby',
            old_name='info',
            new_name='curriculum',
        ),
    ]
