# Generated by Django 5.0.6 on 2024-07-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_rename_info_hobby_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
