# Generated by Django 5.0.6 on 2024-07-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_hobby_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
