# Generated by Django 5.0.6 on 2024-07-15 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_curriculum_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='address',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='city',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='state',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='zipcode',
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(max_length=120, verbose_name='Nom')),
                ('firstname', models.CharField(blank=True, max_length=120, null=True, verbose_name='Prénom')),
                ('address', models.CharField(blank=True, max_length=120, null=True, verbose_name='Adresse')),
                ('city', models.CharField(blank=True, max_length=120, null=True, verbose_name='Ville')),
                ('state', models.CharField(blank=True, max_length=120, null=True, verbose_name='Pays')),
                ('zipcode', models.CharField(blank=True, max_length=120, null=True, verbose_name='Code postal')),
                ('phone', models.CharField(blank=True, max_length=120, null=True, verbose_name='Téléphone')),
                ('active', models.BooleanField(default=False)),
                ('curriculum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='curriculum.curriculum')),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Infos',
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='infos',
            field=models.ManyToManyField(blank=True, related_name='infos', to='curriculum.info'),
        ),
    ]
