# Generated by Django 5.0.6 on 2024-07-15 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_alter_curriculum_created_at_alter_curriculum_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_experience', models.CharField(max_length=120, verbose_name="titre de la l'expérience")),
                ('description_experience', models.TextField(verbose_name="description de l'expérience")),
                ('business', models.CharField(blank=True, max_length=120, null=True, verbose_name='école ou entreprise')),
                ('start_date_of_experience', models.DateField(blank=True, null=True, verbose_name="date de début de l'expérience")),
                ('end_date_of_experience', models.DateField(blank=True, null=True, verbose_name="date de fin de l'expérience")),
                ('location_experience', models.CharField(max_length=100, verbose_name="lieu de l'expérience")),
                ('Curriculum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience_info', to='curriculum.curriculum')),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expériences',
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='experiences',
            field=models.ManyToManyField(blank=True, related_name='experiences', to='curriculum.experience'),
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_formation', models.CharField(max_length=120, verbose_name='titre de la formation')),
                ('description_formation', models.TextField(verbose_name='description de la formation')),
                ('business', models.CharField(blank=True, max_length=120, null=True, verbose_name='école ou entreprise')),
                ('start_date_of_formation', models.DateField(blank=True, null=True, verbose_name='date de début de la formation')),
                ('end_date_of_formation', models.DateField(blank=True, null=True, verbose_name='date de fin de la formation')),
                ('location_formation', models.CharField(max_length=100, verbose_name='lieu de la formation')),
                ('curriculum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formation_info', to='curriculum.curriculum')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='formations',
            field=models.ManyToManyField(blank=True, related_name='formations', to='curriculum.formation'),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_language', models.CharField(max_length=120, verbose_name='titre de la langue')),
                ('niveau_language', models.CharField(choices=[('Débutant', 'Débutant'), ('Intermédiaire', 'Intermédiaire'), ('Avancé', 'Avancé')], max_length=120, verbose_name='niveau de la langue choisie')),
                ('Curriculum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_info', to='curriculum.curriculum')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='languages', to='curriculum.language'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_skill', models.CharField(max_length=120, verbose_name='titre de la compétence')),
                ('Curriculum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_info', to='curriculum.curriculum')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.AddField(
            model_name='curriculum',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='skills', to='curriculum.skill'),
        ),
    ]
