# Generated by Django 5.0.6 on 2024-07-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_experience_curriculum_experiences_formation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formation',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='language',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
