# Generated by Django 5.0.6 on 2024-07-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_experience_active_formation_active_language_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date de naissance de la personne'),
        ),
        migrations.AddField(
            model_name='info',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='email de la personne'),
        ),
        migrations.AddField(
            model_name='info',
            name='motivation',
            field=models.TextField(blank=True, null=True, verbose_name='motivation de la personne'),
        ),
        migrations.AddField(
            model_name='info',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='lieu de naissance de la personne'),
        ),
        migrations.AddField(
            model_name='info',
            name='type_of_contract',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='type de contrat'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='active',
            field=models.BooleanField(default=False, verbose_name='curriculum is active?'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='active',
            field=models.BooleanField(default=False, verbose_name='curriculum is active?'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='active',
            field=models.BooleanField(default=False, verbose_name='curriculum is active?'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='active',
            field=models.BooleanField(default=False, verbose_name='curriculum is active?'),
        ),
        migrations.AlterField(
            model_name='info',
            name='active',
            field=models.BooleanField(default=False, verbose_name='curriculum is active?'),
        ),
        migrations.AlterField(
            model_name='info',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='adresse de la personne'),
        ),
        migrations.AlterField(
            model_name='info',
            name='city',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='info',
            name='firstname',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='prénom de la personne'),
        ),
        migrations.AlterField(
            model_name='info',
            name='lastname',
            field=models.CharField(max_length=120, verbose_name='nom de la personne'),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='téléphone de la personne'),
        ),
        migrations.AlterField(
            model_name='info',
            name='state',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='état'),
        ),
        migrations.AlterField(
            model_name='info',
            name='zipcode',
            field=models.IntegerField(blank=True, null=True, verbose_name='code postal'),
        ),
        migrations.AlterField(
            model_name='language',
            name='active',
            field=models.BooleanField(default=False, verbose_name='curriculum is active?'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='active',
            field=models.BooleanField(default=False, verbose_name='curriculum is active?'),
        ),
    ]
