# Generated by Django 5.0.6 on 2024-07-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_info_date_of_birth_info_email_info_motivation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='photo de la personne'),
        ),
    ]
