# Generated by Django 5.0.6 on 2024-07-21 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0013_experience_user_formation_user_hobby_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='experiences',
            field=models.ManyToManyField(blank=True, related_name='curriculums', to='curriculum.experience'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='formations',
            field=models.ManyToManyField(blank=True, related_name='curriculums', to='curriculum.formation'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='hobbies',
            field=models.ManyToManyField(blank=True, related_name='curriculums', to='curriculum.hobby'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='infos',
            field=models.ManyToManyField(blank=True, related_name='curriculums', to='curriculum.info'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='curriculums', to='curriculum.language'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='curriculums', to='curriculum.skill'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
