# Generated by Django 5.0.6 on 2024-07-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0014_alter_curriculum_experiences_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='user',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hobby',
            name='user',
        ),
        migrations.RemoveField(
            model_name='info',
            name='user',
        ),
        migrations.RemoveField(
            model_name='language',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='active',
            field=models.BooleanField(default=True, verbose_name='curriculum is active?'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='active',
            field=models.BooleanField(default=True, verbose_name='curriculum is active?'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='active',
            field=models.BooleanField(default=True, verbose_name='curriculum is active?'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='active',
            field=models.BooleanField(default=True, verbose_name='curriculum is active?'),
        ),
        migrations.AlterField(
            model_name='info',
            name='active',
            field=models.BooleanField(default=True, verbose_name='curriculum is active?'),
        ),
        migrations.AlterField(
            model_name='language',
            name='active',
            field=models.BooleanField(default=True, verbose_name='curriculum is active?'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='active',
            field=models.BooleanField(default=True, verbose_name='curriculum is active?'),
        ),
    ]
