# Generated by Django 5.0.6 on 2024-07-28 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0015_remove_experience_user_remove_formation_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='active',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='active',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='active',
        ),
        migrations.RemoveField(
            model_name='hobby',
            name='active',
        ),
        migrations.RemoveField(
            model_name='info',
            name='active',
        ),
        migrations.RemoveField(
            model_name='language',
            name='active',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='active',
        ),
    ]
